/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dancc' at '10/14/16 10:23 AM' with Gradle 2.14.1
 *
 * @author dancc, @date 10/14/16 10:23 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
